FROM scratch

MAINTAINER Arnaud Dubois <adubois.personnel@gmail.com>

LABEL name="Docker build of Raspbian 12 Bookworm armhf"

ADD bookworm-armhf-ext4 /

ENV DEBIAN_FRONTEND noninteractive

RUN chmod -R 777 /var/cache/man

RUN apt -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update 

CMD ["/bin/bash"]
